version: '2.1'

services:
  web:
    image: elkozmon/zoonavigator-web:0.5.0
    container_name: zoonavigator-web
    ports:
     - "7070:7070"
    environment:
      WEB_HTTP_PORT: 7070
      API_HOST: "api"
      API_PORT: 9000
    depends_on:
     - api
  api:
    image: elkozmon/zoonavigator-api:0.5.0
    container_name: zoonavigator-api
    environment:
      API_HTTP_PORT: 9000