version: "3.9"

services:
  zookeeper-navi:
    ports:
      - "9000:9000"
    image: "elkozmon/zoonavigator:latest"
    restart: unless-stopped
    container_name: "zoonavigator"
    environment:
      - "HTTP_PORT=9000"